# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible.json
# This is a basic workflow to help you get started with Actions.
name: Docs-Linting

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Vale
      uses: errata-ai/vale-action@v1.4.2
      with:
        debug: true
        files: all
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
