name: Vale-Linting
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Vale
        uses: errata-ai/vale-action@v1.4.2
        with:
          debug: true
          styles: |
            https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
        env:
            GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
